version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4:6.18
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_EXTERNAL}
    volumes:
      - ./pgadmin:${PG_ADMIN_DATA}
    env_file:
      - .env
    restart: always
    networks:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_EXTERNAL}
    volumes:
      - ./postgres-data:${POSTGRES_DATA}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - postgres

  nest-api:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    image: app:app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG}:${DEBUG}
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
    networks:
      - postgres

volumes:
  pgadmin:
  postgres-data:


networks:
  postgres:
    driver: bridge