version: "3.9"
services:
  nest-api:
    container_name: app
    image: app/partyzzzan77:app
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - PORT = ${PORT}
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG}:${DEBUG}
    volumes:
      - ./:/app
      - ignore:/app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    networks:
      - postgres

  postgres:
    container_name: postgres
    image: app/postgres:postgres
    build:
      dockerfile: src/Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_EXTERNAL}
    volumes:
      - ./postgres-data:${POSTGRES_DATA}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:6.18
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_EXTERNAL}
    volumes:
      - ./pgadmin:${PG_ADMIN_DATA}
    env_file:
      - .env
    restart: always
    networks:
      - postgres

volumes:
  ignore:
  pgadmin:
  postgres-data:


networks:
  postgres:
    driver: bridge